[env]
URL = "https://localhost/"

# not work
[target.x86_64-unknown-linux-gnu]
# linker = "x86_64-unknown-linux-gnu-gcc"
linker = "rust-lld"
rustflags = ["-C", "linker-flavor=ld.lld"]

[target.x86_64-unknown-linux-musl]
# linker = "x86_64-linux-musl-gcc"
linker = "rust-lld"
rustflags = ["-C", "linker-flavor=ld.lld"]